<a href="https://colab.research.google.com/github/FadelAnfasha/MachineLearning/blob/main/W9_ConciseImplementationOfLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install d2l==0.17.0

     |████████████████████████████████| 83 kB 1.2 MB/s 


In [2]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):  
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-0.6577624 ,  1.2231966 ],
        [-0.9617342 , -0.22569118],
        [-0.72321695, -0.36961207],
        [ 0.49422064, -1.3844305 ],
        [-0.84578013, -1.4670998 ],
        [ 1.3899914 , -0.6952603 ],
        [ 0.72832745,  0.0699498 ],
        [ 0.35963953,  0.24320304],
        [ 0.0257921 ,  0.05966534],
        [ 2.1404479 ,  0.94609   ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[-1.2762171],
        [ 3.04168  ],
        [ 4.01799  ],
        [ 9.905978 ],
        [ 7.4882836],
        [ 9.3480625],
        [ 5.4145875],
        [ 4.0856647],
        [ 4.035683 ],
        [ 5.256146 ]], dtype=float32)>)

In [5]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
loss = tf.keras.losses.MeanSquaredError()

In [8]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000160
epoch 2, loss 0.000102
epoch 3, loss 0.000102


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([0.00040281 0.00041556], shape=(2,), dtype=float32)
error in estimating b [-0.00114298]
